In [1]:
import subprocess
import sys

import json

import numpy as np
from numpy import float32

In [2]:
#### 11. Create a 3x3 identity matrix (★☆☆)
_11 = np.eye(3, dtype=float32)
_11

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [3]:
#### 12. Create a 3x3x3 array with random values (★☆☆)
_rng = np.random.default_rng(0x42)
_12 = _rng.normal(0, 1.0, size = (3, 3))
_12

array([[ 0.54103331, -0.5399175 , -0.49271523],
       [-1.05958543, -1.32601428, -1.55175407],
       [ 0.50182805,  1.11961627,  0.44104604]])

In [4]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
_rng = np.random.default_rng(0x42)
_13 = _rng.normal(0, 1.0, size = (10, 10))
_13.min(), _13.max()

(-2.6163209383434505, 2.471384008303433)

In [5]:
#### 14. Create a random vector of size 30 and find the mean value (★☆o☆)
_rng = np.random.default_rng(0x42)
_14 = _rng.normal(0, 1.0, size = 30)
_14.mean(), _14.sum() / len(_14)

(-0.08629277927674271, -0.08629277927674271)

In [6]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
_15 = np.zeros(shape=(6, 6))
_15[:, (0, -1)] = 1
_15[(0, -1), :] = 1
_15

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [7]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
_16 = np.zeros(shape=(_15.shape[0] + 2, _15.shape[1] + 2))
_16[1:-1, 1:-1] = _15
_16

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
#### 17. What is the result of the following expression? (★☆☆)
"""
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```
"""
assert np.isnan(0 * np.nan)
assert not (np.nan == np.nan)
assert not (np.inf > np.nan)
assert np.isnan(np.nan - np.nan)
assert (np.nan in set([np.nan]))
assert not (0.3 == 3 * 0.1) # Only this is interesting, everything else is arbitrary numpy stuff

In [9]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
_18 = np.zeros((5, 5), dtype=float32)
for x in range(4):
    _18[x + 1, x] = x + 1
_18

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]], dtype=float32)

In [10]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
_19 = np.zeros((8, 8), dtype=float32)
_19[::2, ::2] = 1
_19[1::2, 1::2] = 1
_19

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]], dtype=float32)

In [11]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
_20 = np.arange(0, 6 * 7 * 8).reshape((6, 7, 8))

num_x = 100 // (7 * 8) # 1
temp = 100 % (7 * 8) # 44 == 100 - 7 * 8
num_y = temp // 8 # 5
num_z = temp % 8 # 4
assert 100 == _20[(num_x, num_y, num_z)]
print(f"{(num_x, num_y, num_z)=}")

(num_x, num_y, num_z)=(1, 5, 4)
