In [1]:
import subprocess
import sys

import json

import numpy as np

In [2]:
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
_21_1 = np.tile(np.array([1, 0]), reps = 4)
_21_2 = np.tile(np.array([0, 1]), reps = 4)
_21 = np.tile(np.append(_21_1, _21_2), reps=4).reshape((8, 8))
_21

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [3]:
#### 22. Normalize a 5x5 random matrix (★☆☆)
_rng = np.random.default_rng(0x42)
_22 = _rng.uniform(-10, 10, size = (5, 5)).astype(np.float32)
_22_mean = _22.mean()
_22_std = _22.std()
_22 = (_22 - _22_mean) / (_22_std)
assert np.isclose(_22.mean(), 0.0, atol = 1e-5)
assert np.isclose(_22.std(), 1.0, atol = 1e-5)
_22

array([[ 1.739852  ,  0.86338425, -1.4894558 ,  0.60314035,  0.02721341],
       [ 1.456262  , -1.3759916 , -0.10561122, -0.0201347 ,  1.6831282 ],
       [ 1.2389948 ,  0.24433719, -1.2423449 ,  1.010823  , -0.8948504 ],
       [-0.4989425 , -1.2239528 , -0.8033057 ,  0.01482   , -0.7675207 ],
       [-0.8318708 ,  0.6666091 ,  0.36170393, -1.4146595 ,  0.75837195]],
      dtype=float32)

In [4]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
_23_rgba_color_dtype = np.dtype([
    ('r', np.uint8),  # Red channel
    ('g', np.uint8),  # Green channel
    ('b', np.uint8),  # Blue channel
    ('a', np.uint8)   # Alpha channel for transparency
])
example_color = np.array((255, 0, 0, 128), dtype=_23_rgba_color_dtype)

print("Custom dtype:", _23_rgba_color_dtype)
print("Example RGBA color:", example_color)

Custom dtype: [('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
Example RGBA color: (255, 0, 0, 128)


In [5]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
_rng = np.random.default_rng(0x42)
_24_1 = _rng.normal(0, 1.0, size = (5, 3))
_24_2 = _rng.normal(0, 1.0, size = (3, 2))
_24 = _24_1 @ _24_2 # alternativey np.matmul(_24_1, _24_2)
_24

array([[-0.64113077, -0.03731875],
       [-2.04442066,  0.06507782],
       [-0.36025289,  0.02977759],
       [-0.71406571,  0.0167476 ],
       [ 3.44711721, -0.19350569]])

In [6]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
_rng = np.random.default_rng(0x42)
_25 = _rng.normal(5, 3, size = 20)
_25 = np.where((_25 >= 3) & (_25 <= 8), -_25, _25)
_25

array([-6.62309994, -3.38024749, -3.52185431,  1.8212437 ,  1.02195715,
        0.34473778, -6.50548414,  8.35884881, -6.32313812, -5.85645503,
       -5.87884011, -4.62317105, -7.91871186,  2.67128556,  8.21535528,
       -4.52951634, -4.83424769,  1.32495589, -5.23976928, 12.41415202])

In [8]:
#### 26. What is the output of the following script? (★☆☆)
assert 9 == sum(range(5),-1)
from numpy import *
assert 10 == sum(range(5),-1)

# Reason for this is that we overwrite the python internal sum by the numpy sum:
from numpy import sum as np_sum
assert 10 == np_sum(range(5), -1)

from builtins import *
assert 9 == sum(range(5),-1)

In [28]:
#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z = np.array([0, -1, 3, 8, 12], dtype=np.int32)
try:
    Z**Z
except ValueError:
    print("Trying to take integeger power to negative exponent.")
assert ((2 << Z >> 2) == ((2 << Z) >> 2)).all()
assert ((Z <- Z) == (Z < (-Z))).all()
1j*Z # 1j is complex unit we get j * Z basically here
(((Z / 2) / 3) == (Z/2/3)).all()
try:
    Z<Z>Z
except ValueError:
    print("Ambiguous Truth value")

Trying to take integeger power to negative exponent.
Ambiguous Truth value


In [35]:
#### 28. What are the result of the following expressions? (★☆☆)
# Div0 -> nan
_28_1 = np.array(0) / np.array(0)
# Div0 -> 0
_28_2 = np.array(0) // np.array(0)
# Div0 -> [0.]
_28_3 = np.array([np.nan]).astype(int).astype(float)

_28_1, _28_2, _28_3

/var/folders/dq/z5syqybd1z96g4ny_n5nr9rc0000gn/T/ipykernel_4189/879970688.py:3: RuntimeWarning: invalid value encountered in divide
  _28_1 = np.array(0) / np.array(0)
/var/folders/dq/z5syqybd1z96g4ny_n5nr9rc0000gn/T/ipykernel_4189/879970688.py:5: RuntimeWarning: divide by zero encountered in floor_divide
  _28_2 = np.array(0) // np.array(0)
/var/folders/dq/z5syqybd1z96g4ny_n5nr9rc0000gn/T/ipykernel_4189/879970688.py:7: RuntimeWarning: invalid value encountered in cast
  _28_3 = np.array([np.nan]).astype(int).astype(float)


(nan, 0, array([0.]))

In [40]:
#### 29. How to round away from zero a float array ? (★☆☆)
_rng = np.random.default_rng(0x42)
_29 = _rng.normal(0, 1.0, size = 10)
np.where(_29 > 0, np.ceil(_29), np.floor(_29))

array([ 1., -1., -1., -2., -2., -2.,  1.,  2.,  1.,  1.])

In [91]:
#### 30. How to find common values between two arrays? (★☆☆)
_rng = np.random.default_rng(0x42)
_30_1 = np.arange(-12, 5)
_rng.shuffle(_30_1)
_30_2 = np.arange(-3, 20)
_rng.shuffle(_30_2)

_30_shared = _30_1[np.nonzero(np.where(np.isin(_30_1, _30_2), 1, 0))]

# Alternatively this can be solved by using np.intersectid
_30_shared_alternative = np.intersect1d(_30_1, _30_2)

assert set(_30_shared) == set(_30_shared_alternative)