In [1]:
import subprocess
import sys

import json

import numpy as np

In [2]:
#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
# np.seterr(all="ignore")
# Alternativly
# import warnings
# warnings.filterwarnings("ignore")

In [3]:
#### 32. Is the following expressions true? (★☆☆)
# From np.emath.sqrt docstring:
# > For negative input elements, a complex value is returned (unlike `numpy.sqrt` which returns NaN).
assert np.sqrt(-1) != np.emath.sqrt(-1)

/var/folders/dq/z5syqybd1z96g4ny_n5nr9rc0000gn/T/ipykernel_4893/1627491694.py:4: RuntimeWarning: invalid value encountered in sqrt
  assert np.sqrt(-1) != np.emath.sqrt(-1)


In [9]:
#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
_33_today = np.datetime64("today", "D")
print(f"Today is {_33_today}, tomorrow is {_33_today + 1} and yesterday was {_33_today - 1}.")

Today is 2024-04-27, tomorrow is 2024-04-28 and yesterday was 2024-04-26.


In [15]:
#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
start_date = np.datetime64("2016-07-01")
end_date = np.datetime64("2016-08-01")

_34 = np.arange(start_date, end_date)
_34

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [48]:
#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
_rng = np.random.default_rng(0x42)
_35_A = _rng.normal(0, 1.0, size = (5, 5))
_35_B = _rng.normal(0, 1.0, size = (5, 5))
_35_A_copy = _35_A.copy()
_35_B_copy = _35_B.copy()

np.add(_35_A, _35_B, out = _35_B)
np.divide(_35_A, -2.0, out = _35_A)
np.multiply(_35_A, _35_B, out = _35_A)
assert np.allclose(_35_A, (_35_A_copy + _35_B_copy) * (- _35_A_copy / 2))

In [81]:
#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
_rng = np.random.default_rng(0x42)
_36 = _rng.uniform(-5, 12, size = (5, 5))

# This works even for negative ones
_36_1 = np.where(_36 >= 0, np.floor(_36), np.ceil(_36))
_36_2 = _36.astype(np.int64)
_36_3 = np.trunc(_36)
_36_4 = np.sign(_36) * (np.floor(np.sign(_36) * _36))

assert np.allclose(_36_1, _36_2, atol = 1e-4)
assert np.allclose(_36_2, _36_3, atol = 1e-4)
assert np.allclose(_36_3, _36_4, atol = 1e-4)

In [123]:
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
_rng = np.random.default_rng(0x42)

_37 = _rng.normal(0, 3.0, size = (5, 5))
_37[:, 4] = np.arange(0, 4 + 1) - _37[:, :4].sum(axis = 1)

assert np.allclose(_37.sum(axis = 1), np.arange(0, 4 + 1))
_37

array([[ 1.62309994, -1.61975251, -1.47814569, -3.1787563 ,  4.65355457],
       [-4.65526222,  1.50548414,  3.35884881,  1.32313812, -0.53220884],
       [ 0.87884011, -0.37682895,  2.91871186, -2.32871444,  0.90799143],
       [-0.47048366, -0.16575231, -3.67504411,  0.23976928,  7.0715108 ],
       [-0.21752302, -1.20005224,  1.17818913,  2.97139015,  1.26799599]])

In [128]:
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
_rng = np.random.default_rng(0x42)
_38 = _rng.uniform(-100, 100, size = 10).astype(np.int64)
_38

array([ 84,  38, -85,  24,  -5,  69, -79, -12,  -7,  81])

In [133]:
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
_rng = np.random.default_rng(0x42)
_38 = _rng.uniform(0, 1, size = 10)
np.where(np.isclose(_38, 0), 0.3, _38)
np.where(np.isclose(_38, 1.0), 0.7, _38)

array([0.92373388, 0.69281813, 0.07293478, 0.62425381, 0.4725191 ,
       0.84901876, 0.10282827, 0.43752488, 0.46004468, 0.90878931])

In [135]:
#### 40. Create a random vector of size 10 and sort it (★★☆)
_rng = np.random.default_rng(0x42)
_40 = _rng.normal(0, 1, size = 10)
_40.sort()
_40

array([-1.55175407, -1.32601428, -1.05958543, -0.5399175 , -0.49271523,
        0.28548501,  0.44104604,  0.50182805,  0.54103331,  1.11961627])