In [1]:
import subprocess
import sys

import json

import numpy as np

import timeit
import matplotlib.pyplot as plt

In [3]:
#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
# See also problem 23
_51_rgba_color_dtype = np.dtype([
    ('x', np.float32),
    ('y', np.float32),
    ('r', np.uint8),
    ('g', np.uint8),
    ('b', np.uint8),
])

In [61]:
#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
_rng = np.random.default_rng(0x52)

n = 5
_52 = _rng.normal(0, 1, size = (5, 2))

# This has two big problems, we're looping instead of using broadcasting and the dists matrix is much larger
# than how we need it, we only need a strict upper (or lower) triangle matrix.
# The memory part doesn't matter, but the broadcasting improvement should be implemented.
dists = np.zeros((n, n))
for c1 in range(n):
    for c2 in range(n):
        dists[c1, c2] = np.sqrt(((_52[c1] - _52[c2])**2).sum())
dists

# Better solution:
diffs = _52[:, np.newaxis, :] - _52[np.newaxis, :, :]
dists2 = np.sqrt((diffs**2).sum(axis=2))

In [66]:
#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
_rng = np.random.default_rng(0x52)
_53 = _rng.normal(0, 1, 5).astype(np.float32)
_53_int = _53.astype(np.int32, copy=False)
_53_int

array([1, 1, 1, 0, 0], dtype=int32)

In [70]:
#### 54. How to read the following file? (★★☆)
from io import StringIO

_54_text = """
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
"""
np.genfromtxt(StringIO(_54_text), delimiter=",", dtype = np.float32, filling_values=np.nan)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]], dtype=float32)

In [82]:
#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
_rng = np.random.default_rng(0x52)
_55 = _rng.normal(0, 1, (3, 2, 3)).astype(np.float32)

for idx, x in np.ndenumerate(_55):
    print(idx, x)

(0, 0, 0) 1.7281629
(0, 0, 1) 1.0269761
(0, 0, 2) 1.108406
(0, 1, 0) -0.9711915
(0, 1, 1) -0.60389626
(0, 1, 2) -0.75932604
(1, 0, 0) -1.7068653
(1, 0, 1) -0.414562
(1, 0, 2) 0.86499995
(1, 1, 0) 0.19078933
(1, 1, 1) -0.21903157
(1, 1, 2) -1.5436639
(2, 0, 0) 1.8427534
(2, 0, 1) -1.4766527
(2, 0, 2) 1.1324579
(2, 1, 0) -0.8171581
(2, 1, 1) 0.16262788
(2, 1, 2) 0.101823494


In [85]:
#### 56. Generate a generic 2D Gaussian-like array (★★☆)
_rng = np.random.default_rng(0x56)
_56 = _rng.normal(0, 1, (5, 5)).astype(np.float32)
_56

array([[-1.6479093 , -0.25462016,  0.6708038 ,  0.7228996 , -0.80873966],
       [ 0.51022094,  0.3950654 ,  0.11043056,  0.22358987, -1.3446206 ],
       [-0.13632324, -0.21830979,  1.602185  ,  0.09255192, -2.451026  ],
       [ 1.1897782 ,  1.6874334 , -0.0354345 ,  1.731924  ,  0.91101205],
       [ 0.10659432, -1.6231908 , -1.0537273 ,  0.02142728,  0.22608486]],
      dtype=float32)

In [96]:
#### 57. How to randomly place p elements in a 2D array? (★★☆)
_rng = np.random.default_rng(0x57)
_57 = np.zeros((5, 7))
_57 = np.where(_rng.choice([True, False], _57.shape), 1, _57)

In [110]:
#### 58. Subtract the mean of each row of a matrix (★★☆)
_rng = np.random.default_rng(0x58)
_58 = _rng.normal(0, 1, (8, 5))
_58 - _58.mean(axis = 1)[:, np.newaxis]

array([[-0.2746867 , -0.08338013, -0.60160101,  0.89828293,  0.06138491],
       [ 0.5635966 ,  0.59340119, -0.86919332,  1.13936004, -1.42716451],
       [-1.41823169, -0.86379671, -0.47512984,  0.71911068,  2.03804756],
       [-0.89731246,  0.20202847,  0.24669589,  0.38999539,  0.0585927 ],
       [ 0.61561159, -0.41748136, -0.39920759, -0.64757707,  0.84865443],
       [-0.45438969,  0.31567042, -0.5927223 , -0.04815004,  0.77959162],
       [ 0.5499958 , -1.19627291,  1.10427294, -0.97876266,  0.52076683],
       [ 1.38550516, -0.73004133,  0.94381635, -0.58748572, -1.01179446]])

In [118]:
#### 59. How to sort an array by the nth column? (★★☆)
_rng = np.random.default_rng(0x59)
_59 = _rng.normal(0, 1, (2, 3, 4))
n = 2
_59.sort(axis = n)
print(_59)

[[[-0.511917   -0.27390557  0.29799124  1.07507955]
  [ 0.11782752  0.3367676   0.51608631  0.94066239]
  [-1.15096743 -0.88881272  0.57823553  1.07183762]]

 [[-0.60053665  0.01505873  0.15784276  0.34355859]
  [-2.11071255 -0.97452601 -0.10107949  0.75299995]
  [-0.7767985  -0.73390124 -0.07100698  0.92716733]]]


In [131]:
#### 60. How to tell if a given 2D array has null columns? (★★☆)
# Assuming they mean columns that sum to 0
_rng = np.random.default_rng(0x60)
_60 = _rng.normal(0, 1, (4, 5))
np.isclose(_60.sum(axis = 0), 0.0, atol = 1e-4).any()

False