In [1]:
import subprocess
import sys

import json

import numpy as np

import timeit
import matplotlib.pyplot as plt

In [2]:
#### 61. Find the nearest value from a given value in an array (★★☆)
# see also problem 50
_rng = np.random.default_rng(0x2024_04_27)
arr = _rng.normal(0, 1, (5, 3))
vec = np.array([0, 1, 2]).astype(np.float64)
print(arr, vec)

deltas = arr - vec[np.newaxis, :]
norms: np.ndarray = np.linalg.norm(deltas, axis = 1)

idx = norms.argmin()
idx, arr[idx, :]

[[ 0.90806217 -1.12210736  0.81088513]
 [-0.30877901  0.24100518  0.4002118 ]
 [-0.82135085 -0.70663526  0.94614158]
 [-0.41061916  1.65090848 -0.98328309]
 [ 0.43512441  0.0126393  -0.36581836]] [0. 1. 2.]


(1, array([-0.30877901,  0.24100518,  0.4002118 ]))

In [3]:
#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
_rng = np.random.default_rng(0x2024_04_27)
_62_1 = _rng.normal(0, 1, (1, 3))
_62_2 = _rng.normal(0, 1, (3, 1))

sum(x + y for x, y in zip(_62_1[0], _62_2))

array([0.92927792])

In [4]:
#### 63. Create an array class that has a name attribute (★★☆)
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name="No Name"):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        # This method is called when the object is created and it helps
        # in setting up the additional attributes if they aren't explicitly set.
        # Here, we copy the name attribute from the parent if it is not set.
        if obj is None: return
        self.name = getattr(obj, 'name', "No Name")

arr = NamedArray([1, 2, 3, 4], name="My Array")
print(arr)
print("Name:", arr.name)

[1 2 3 4]
Name: My Array


In [5]:
#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
_rng = np.random.default_rng(0x2024_04_27)
_62 = _rng.normal(0, 1, 6)
_62_idxs = np.array([1, 3, 3, 5])
print(_62)
np.add.at(_62, _62_idxs, 1)
print(_62)

[ 0.90806217 -1.12210736  0.81088513 -0.30877901  0.24100518  0.4002118 ]
[ 0.90806217 -0.12210736  0.81088513  1.69122099  0.24100518  1.4002118 ]


In [6]:
#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [7]:
#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
size_per_ubyte = np.iinfo(np.ubyte).max - np.iinfo(np.ubyte).min

total_number = size_per_ubyte * size_per_ubyte * 3
total_number

195075

In [8]:
#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
_rng = np.random.default_rng(0x67)
x = _rng.normal(0, 1, (2, 3, 2, 3))
x.sum(axis = (2,3))

array([[-1.21213493, -5.42838849,  1.04099272],
       [ 0.45355494, -0.0345347 ,  1.45636618]])

In [9]:
#### 69. How to get the diagonal of a dot product? (★★★)
# Still WIP
_rng = np.random.default_rng(0x67)
x = _rng.normal(0, 1, (2, 3))
y = _rng.normal(0, 1, (3, 2))

diagonal = np.einsum('ij,jk->i', x, y)
print(diagonal.sum())
print((np.dot(x, y) * np.eye(2)).sum())

2.9826868736666405
4.580794392099438


In [10]:
#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)