In [1]:
import subprocess
import sys

import json

import numpy as np

import timeit
import matplotlib.pyplot as plt

In [2]:
#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [3]:
#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [4]:
#### 72. How to swap two rows of an array? (★★★)
_rng = np.random.default_rng(0x72)

_72 = _rng.normal(0, 1, (10, 3))

idx0 = 0
idx1 = 1

print(_72)
np.add(_72[idx0], _72[idx1], out = _72[idx1])
np.subtract(_72[idx1], _72[idx0], out = _72[idx0])
np.subtract(_72[idx1], _72[idx0], out = _72[idx1])
print()
print(_72)

[[-0.8519482   0.2126255  -0.89265491]
 [ 0.88251863  1.19658027  0.20003868]
 [-0.38033968  0.14525026 -0.25603755]
 [-0.66479126 -0.41777796  0.12305976]
 [ 0.8513774   0.41682765 -0.79558598]
 [-1.8116868  -0.99533316 -0.56498876]
 [ 0.90341554 -0.2427454  -1.64602017]
 [ 1.15811154  1.09589927  0.11841377]
 [-1.35878162 -0.48216199  0.14599539]
 [ 0.23073132 -0.80159304 -0.69721493]]

[[ 0.88251863  1.19658027  0.20003868]
 [-0.8519482   0.2126255  -0.89265491]
 [-0.38033968  0.14525026 -0.25603755]
 [-0.66479126 -0.41777796  0.12305976]
 [ 0.8513774   0.41682765 -0.79558598]
 [-1.8116868  -0.99533316 -0.56498876]
 [ 0.90341554 -0.2427454  -1.64602017]
 [ 1.15811154  1.09589927  0.11841377]
 [-1.35878162 -0.48216199  0.14599539]
 [ 0.23073132 -0.80159304 -0.69721493]]
