In [1]:
import subprocess
import sys

import json

import numpy as np

import timeit
import matplotlib.pyplot as plt

In [3]:
#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
_98_X = np.array([1.0, 2.0])
_98_Y = np.array([0.0, 1.0])

v = _98_X - _98_Y
_norm = np.linalg.norm(v)
v = v / _norm

# Samples 1 more so we get both end point
n_samples = 10
dt = _norm / n_samples

samples = [_98_Y + i * dt * v for i in range(n_samples + 1)]
samples

[array([0., 1.]),
 array([0.1, 1.1]),
 array([0.2, 1.2]),
 array([0.3, 1.3]),
 array([0.4, 1.4]),
 array([0.5, 1.5]),
 array([0.6, 1.6]),
 array([0.7, 1.7]),
 array([0.8, 1.8]),
 array([0.9, 1.9]),
 array([1., 2.])]